### ISSUE TITLE
ValueError: high is out of bounds for int32

### ISSUE THREAD

**Issue by MartaUch** [polimi-ispl/icpr2020dfdc#42]
Hello,
I'm getting error "ValueError: high is out of bounds for int32" after running the train_binclass.py code:
![Zrzut ekranu 2021-04-21 153753](https://user-images.githubusercontent.com/28823253/115563301-ae2f9180-a2b7-11eb-845f-3c24c96b27f2.png)

Do you know how can I fix it?

**Comment by CrohnEngineer** [comment]
Hey @MartaUch ,

seems to me that there is some kind of problem in your DataFrame `['name']` field.
Can you please check if the structure of the dataset as is represented in the file `'List_of_testing_videos.txt'` is coherent with the one you actually have in your `--source` argument (i.e., `Dataset\Celeb_DF_model6`)?
Bests,

Edoardo

**Comment by MartaUch** [comment]
Hi,
I'm sorry, by accident I attached the wrong screenshot. I've already edited my first message. I hope my problem will be more uderstandable now.
Bests,
Marta

**Comment by CrohnEngineer** [comment]
Hey @MartaUch ,

it seems you encountered a small OS mismatch :)
If no `--seed` is provided, the code generates a random number between 0 and 2^32 for initializing the network's weights.
This is accomplished with `np.random.choice(2**32)`, which returns a np.array of default type np.int_ is, which is a C long.
However, for reasons I don't know, in Windows even if the system is 64-bit, the default C long word is 32-bit (see [here ](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine)for explanations): therefore, when you give as higher bound 2^32, numpy cannot create a np.int32 vector of a random number between 0 and 2^32.
Quick fix: provide a `--seed` argument (any random int should be fine), or substitute that instruction with `np.random.randint(2**32, dtype=np.int64)`.
As a side note: all the code has been tested on Ubuntu machines, I cannot guarantee you that similar errors won't happen in the future (hopefully not since python is a cross-platform language).
In any case we are not planning to test and maintain this repo also for Windows users, sorry :( 
You might want to install the Windows Subsystem for Linux (https://ubuntu.com/wsl) and use it for executing our code.
Bests, 

Edoardo
