### ISSUE TITLE
What is the true or false distribution of the test data set ?

### ISSUE THREAD

**Issue by miaoct** [polimi-ispl/icpr2020dfdc#6]
For FF++ datasets , balance or imbalance ?
For DFDC datasets , balance or imbalance ?
thank you

**Comment by nicobonne** [comment]
Hi @miaoct, 

sorry for being late, we somehow missed your question. 
Both dataset are very unbalanced towards fake class, since you can generate plenty of fakes starting from the same real sample.

I leave you the links to the official papers, where you can find more informations about the composition. Here's [FF++](https://arxiv.org/abs/1901.08971) and here's [DFDC](https://arxiv.org/abs/2006.07397)
