### ISSUE TITLE
Question about the returned RuntimeError when using the Celeb-DF dataset

### ISSUE THREAD

**Issue by hzhumsc** [polimi-ispl/icpr2020dfdc#68]
Hi! I am trying to train a model on the Celeb-DF dataset. I have indexed the videos and extracted the faces. I have the corresponding dataframes already. And I modified a little train_binclass.py and split.py so that the path related to celebdf can be passed into the functions. I then tried to run the script but I got this error saying that the calculated padded input size per channel is smaller than the kernel size. May I ask for your help to see why is this happening?

And what is the meaning of the argument **size** in train_binclass.py? It's explained as 'train patch size', but I am not sure what does it mean.

Best regards.

**Comment by hzhumsc** [comment]
![1](https://user-images.githubusercontent.com/55445710/145474613-155acfd1-a547-4530-92cc-4198cb0c8143.PNG)
![2](https://user-images.githubusercontent.com/55445710/145474624-05f38df0-be45-4552-b3cd-73338b802d7e.PNG)

**Comment by hzhumsc** [comment]
Above are the details of the returned error message.

**Comment by CrohnEngineer** [comment]
Hey @hzhumsc ,

the argument `size` in `train_binclass.py` indicates the dimension of the face crop you want to use for training the model, so the dimension of the faces given as input to the network.  
By default, we used 224x224, as you can see in [train_all.sh](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/scripts/train_all.sh).  
Now you're using inputs 16x16 pixels wide: they are really too small, so I suggest you to increase this parameter in order to have something working.  
The error you are receiving is exactly related to that parameter: the EfficientNetB4 has not been designed to work on such small inputs (:
Hope this helps!
Bests,

Edoardo

**Comment by hzhumsc** [comment]
@CrohnEngineer ,

Thanks for you reply, Edoardo! I now see that. I have another question that in the split that you reserved for the Celeb-DF, it seems that it only takes the real videos into consideration?
![3](https://user-images.githubusercontent.com/55445710/145590819-07291cef-3928-4445-ac10-9328c2fbabce.PNG)

Best regards,
hzhumsc

**Comment by CrohnEngineer** [comment]
Hey @hzhumsc ,

> Thanks for you reply, Edoardo! I now see that. 

Good to know! :)

> I have another question that in the split that you reserved for the Celeb-DF, it seems that it only takes the real videos into consideration?

We actually consider also fake videos. You can find a detailed explanation on how the code does it in a comment in this [issue](https://github.com/polimi-ispl/icpr2020dfdc/issues/38).
Let me know if you have other questions!
Bests,

Edoardo

**Comment by hzhumsc** [comment]
Hi @CrohnEngineer ,

I read the comments in that issue, now it's clear to me. Thank you again and hope I didn't bother your time too much. Wish you have a good weekend!

Best,
hzhumsc

**Comment by CrohnEngineer** [comment]
Don't worry, no problem at all!
I'll close the issue now, but feel free to ask other questions here or to open another issue if you have other problems.
Good weekend to you too :)
