### ISSUE TITLE
use pre-trained model to detect my videos, but filter out some specific datasets on the pre-train which may overlap

### ISSUE THREAD

**Issue by hcuve** [polimi-ispl/icpr2020dfdc#71]
Thanks for such a valuable resource.
I have used the face the deepfake dataset from Google which is included in faceforensics, some behavioural experiments, and would like to get detection scores for the specific videos I tested, using one of your pre-trained models but would need to ensure that the specific videos I have are not part of the ore-trained model. Is there a way to filter out specific datasets or sets of videos when using your pre-trained weights

**Comment by nicobonne** [comment]
You can't exclude samples from pretrained weights because there is no direct mapping between data and weights. What you can do is replicate our [split](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/isplutils/split.py) for a given dataset and manually check that your videos do not fall under our training set.

**Comment by hcuve** [comment]
thank you, appreciate the response. I will close the issue now
