### ISSUE TITLE
Training dataset for DFDC

### ISSUE THREAD

**Issue by raprap22** [polimi-ispl/icpr2020dfdc#73]
hallo sir, i wanna ask something about train custom dataset...
so if we wanna train for some dataset we must preprocess the datasets in order base on instructions from readme, and when i want to try, i need for path source train split dfdc. where i can get it or how i can make it ?
thanks sir

**Comment by CrohnEngineer** [comment]
Hi @raprap22 ,

Sorry for the very late reply 🙏   
I am not sure I got your question correctly. I'll try to answer anyway:
1. If you're asking whether training our method on custom datasets is possible, the answer is yes, but we do not provide the code in this repository. This is mainly because this repo is a scientific tool for replicating the results we published in the paper "Video Face Manipulation Detection Through Ensemble of CNNs." In the paper, we only trained and tested on the DFDC and FF++ datasets (but over the years, we added the code for working with CelebDF as well);
2. If you're asking how to reproduce the results using the DFDC dataset, please look at the instructions reported in the [README.md file](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/README.md). You can also look at the previous issues, where we solved some common problems encountered by users over the years.

I hope this helps!
