### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by shengwenjun00** [polimi-ispl/icpr2020dfdc#8]
After I executed make_dataset.sh (only FF++ data was extracted), I executed ‘python train_binclass.py --net=EfficientNetB4’ and a KeyError:'source' appeared. My DataFrame has no source, quality, or original, only ['video','label','videosubject','kp1x','kp1y','kp2x','kp2y','kp3x','kp3y','kp4x ','kp4y','kp5x','kp5y','kp6x','kp6y','conf','left','top','right','bottom','nfaces'] these. What is the problem and how can I solve it. Looking forward to your reply.

**Comment by CrohnEngineer** [comment]
Hey @shengwenjun00 ,

at a first glance, when you are executing `python train_binclass.py` you are not providing neither the path to the DataFrame created with `make_dataset.sh` nor the path to the directory containing the faces extracted from FF++.
If you take a look at [train_all.sh](https://github.com/polimi-ispl/icpr2020dfdc/blob/master/scripts/train_all.sh), you can see how to execute `train_binclass.py` with all the arguments needed in order to make it function properly.
If you encounter any other problem, please give us a more detailed description of your error (the error stack trace of Python's interpreter should be fine).
Cheers :) 

Edoardo
